### ISSUE TITLE
Stub files can no longer undo the class `@NonNull` annotation on, e.g., Optional

### ISSUE THREAD

**Issue by cpovirk** [eisop/checker-framework#321]
Inside Google, we (maybe intentionally, maybe not) have a stub for `java.util.Optional` that undoes [the class `@NonNull` annotation on that type](https://github.com/eisop/jdk/blob/36e42e4279c6d8a47496db8e18983ebbcffcfffe/src/java.base/share/classes/java/util/Optional.java#L86), using [the approach from its `CFComment`](https://github.com/eisop/jdk/blob/36e42e4279c6d8a47496db8e18983ebbcffcfffe/src/java.base/share/classes/java/util/Optional.java#L77-L78). As part of the upgrade from 3.21.4-eisop1 to 3.24.0-eisop1, that stops working. I notice that typetools 3.24.0 still works, so I'm wondering if this is fallout from the eisop `extends @Nullable Object` fixes, similar to https://github.com/eisop/checker-framework/issues/204, or from the eisop stub-file fix of https://github.com/eisop/checker-framework/pull/247. I haven't done any binary searching across releases, though, let alone commits. \[edit: After writing that, I started with `git bisect`. But I ran into trouble because the build process doesn't automatically know which commit of `stubparser` to check out when building older versions.\]

```
$ tail -n +1 X.java mystubs.astub 
==> X.java <==
import org.checkerframework.checker.nullness.qual.Nullable;

interface X {
  java.util.@Nullable Optional<String> o();
}

==> mystubs.astub <==
package java.util;
class Optional<T> {}
```

```
checker-framework-3.21.4-eisop1 $ checker/bin/javac -Astubs=mystubs.astub -processor nullness X.java
warning: /usr/local/google/home/cpovirk/checker-framework-3.21.4-eisop1/mystubs.astub: No supported annotations found! Does stub file /usr/local/google/home/cpovirk/checker-framework-3.21.4-eisop1/mystubs.astub import them?
1 warning
```

```
checker-framework-3.24.0-eisop1 $ checker/bin/javac -Astubs=mystubs.astub -processor nullness X.java
warning: /usr/local/google/home/cpovirk/checker-framework-3.24.0-eisop1/mystubs.astub: No supported annotations found! Does stub file /usr/local/google/home/cpovirk/checker-framework-3.24.0-eisop1/mystubs.astub import them?
X.java:4: error: [type.invalid.annotations.on.use] invalid type: annotations [@Initialized, @Nullable] conflict with declaration of type java.util.Optional
  java.util.@Nullable Optional<String> o();
                                       ^
1 error
1 warning
```

```
checker-framework-3.24.0 $ checker/bin/javac -Astubs=mystubs.astub -processor nullness X.java
warning: /usr/local/google/home/cpovirk/checker-framework-3.24.0/mystubs.astub: No supported annotations found! Does stub file /usr/local/google/home/cpovirk/checker-framework-3.24.0/mystubs.astub import them?
1 warning
```

@amalloy

**Comment by wmdietl** [comment]
@cpovirk Thanks for the detailed report and sorry for the trouble.
I've created a test in #324 and narrowed the issue down to being introduced in #305.

**Comment by cpovirk** [comment]
No worries, and thanks!

(Also: Ooo, I wonder if #305 helps with any of the challenges we've seen when trying to read `@NullMarked` from stub files from our reference checker! (It's been a while, so I forget the details.) And even if not, fixing _any_ missing annotations is a good thing :))

**Comment by wmdietl** [comment]
Yes, #305 should fix parsing annotations e.g. in `package-info.java` files.
Let us get this issue fixed and then you can let us know if you're still running into issues.

**Comment by cpovirk** [comment]
This does fix our issue. Thanks!
