### PR TITLE
Always run Gradle on JDK 21; also run CI tests on JDK 25

### LINKED ISSUE #1115: Run Gradle with a JDK 17 (or 21) and then compile and run tests with different versions
It is getting increasingly harder to run gradle on Java 8:

https://github.com/eisop/checker-framework/pull/1114/commits/9d65e90901256bdabea81bb2a6cbd31e22b6ef82

The reflection-util problem will require that we release a separate version that continues to run on Java 8.

The other gradle plugin dependencies should be fixable by running gradle on one version and then compiling the project and running the tests on a different version.
This is also important, because Gradle will only run on Java 17+ soon.

### PR DESCRIPTION
**Pull request by wmdietl**
Fixes #1115.

The "output version numbers" step shows the expected results:

````
Run which java && ./gradlew --version
/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.442-6/x64/bin/java

------------------------------------------------------------
Gradle 8.13
------------------------------------------------------------

Build time:    2025-02-25 09:22:14 UTC
Revision:      073314332697ba45c16c0a0ce1891fa6794179ff

Kotlin:        2.0.21
Groovy:        3.0.22
Ant:           Apache Ant(TM) version 1.10.15 compiled on August 25 2024
Launcher JVM:  1.8.0_442 (Temurin 25.442-b06)
Daemon JVM:    /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.6-7/x64 (from org.gradle.java.home)
OS:            Linux 6.8.0-1021-azure amd64
````

The non-junit tests fail as expected and show the correct version number:
````
--- expected.txt	2025-04-23 02:22:36.929459964 +0000
+++ out.txt	2025-04-23 02:25:07.040227077 +0000
@@ -1,3 +1,4 @@
+javac 11.0.26
 TwoCheckers.java:28: error: [argument.type.incompatible] incompatible argument for parameter b of TwoCheckers.requiresUntainted.
         requiresUntainted(a);
make[1]: [Makefile:4: all] Error 1 (ignored)
make[1]: *** [Makefile:5: all] Error 1
make: *** [Makefile:11: issue618] Error 2
````

JDK 8 build needs more fixes.
JDK 25 fails because of #1180. But as an experimental JDK, that failure gets ignored and we'll get to #1180 separately.

### CODE REVIEW

**Comment by wmdietl** [comment]
@Ao-senXiong Could you take a look at this PR and see whether the right versions are used?
The nonjunit tests are failing because I'm outputting version information. I'll undo that in `checker/build.gradle` to make those tests pass.

**Comment by Ao-senXiong** [comment]
ok, I will take a look later.

**Comment by wmdietl** [comment]
The last remaining failure is in `cftests-nonjunit on JDK 25-ea`. That test-only failure will be fixed in #1198.
